# PDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.

#ifdef OPLUS_FEATURE_STATS_CALC
obj-$(CONFIG_OPLUS_FEATURE_STATS_CALC) += oplus_stats_calc/
#endif /* OPLUS_FEATURE_STATS_CALC */
